# wordpress-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: afatirahmedfatir/wordpress:k8s
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: wp-config
              key: DB_HOST
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: username
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: password
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: database
        - name: WORDPRESS_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: username
        - name: WORDPRESS_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: password
        - name: WORDPRESS_ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: email
        - name: DOMAIN_NAME
          valueFrom:
            configMapKeyRef:
              name: wp-config
              key: DOMAIN_NAME
        - name: WP_TITLE
          valueFrom:
            configMapKeyRef:
              name: wp-config
              key: WP_TITLE
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: wordpress-pv
          mountPath: /var/www/wordpress
        resources:
          requests:
            cpu: 150m
            memory: 256Mi
          limits:
            cpu: 300m
            memory: 512Mi
        command: ["/bin/bash", "/wp_conf.sh"]
      volumes:
      - name: wordpress-pv
        persistentVolumeClaim:
          claimName: wordpress-pvc