# wordpress-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        env:
        - name: WORDPRESS_DB_HOST
          value: mariadb
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: username
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: password
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: database
        - name: WORDPRESS_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: username
        - name: WORDPRESS_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: password
        - name: WORDPRESS_ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: email
        ports:
        - containerPort: 80
        volumeMounts:
        - name: wordpress-pv
          mountPath: /var/www/html
        resources:
          requests:
            cpu: 150m
            memory: 256Mi
          limits:
            cpu: 300m
            memory: 512Mi
        command: ["/bin/sh", "-c"]
        args:
          - |
            apt-get update && apt-get install -y netcat-openbsd curl;

            curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
            && chmod +x wp-cli.phar \
            && mv wp-cli.phar /usr/local/bin/wp

            until nc -z mariadb 3306; do echo "Waiting for database..."; sleep 3; done;
            mkdir -p /var/www/html;
            cd /var/www/html;
            if ! wp core is-installed --allow-root; then
              echo "[========WP INSTALLATION STARTED========]";
              find /var/www/html/ -mindepth 1 -delete;
              wp core download --allow-root;
              wp core config --dbhost="$WORDPRESS_DB_HOST":3306 --dbname="$WORDPRESS_DB_NAME" --dbuser="$WORDPRESS_DB_USER" --dbpass="$WORDPRESS_DB_PASSWORD" --allow-root;
              wp core install --url="http://localhost" --title="WordPress" --admin_user="$WORDPRESS_ADMIN_USER" --admin_password="$WORDPRESS_ADMIN_PASSWORD" --admin_email="$WORDPRESS_ADMIN_EMAIL" --allow-root;
              wp theme install  twentytwentyfour --activate --allow-root;
            else
              echo "[========WP ALREADY INSTALLED========]";
            fi;
            apache2-foreground;
      volumes:
      - name: wordpress-pv
        persistentVolumeClaim:
          claimName: wordpress-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector:
    app: wordpress
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP