apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-certificates-pvc
spec:
  storageClassName: "oci-bv"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi